### ISSUE TITLE
LSIIR throws ValueError when UH is given

### ISSUE THREAD

**Issue by mgrub** [PTB-M4D/PyDynamic#263]
**Describe the bug**
Calling LSIIR with a full covariance matrix `UH` yields:
```bash
Traceback (most recent call last):
  File "......./code/get_transfer_function.py", line 153, in <module>
    b, a, tau, uab = LSIIR(H=H, UH=UH, Nb=3, Na=6, f=ff, Fs=Fs, tau=2, inv=True, mc_runs=100, verbose=False)
  File "~/python_venv/cim_2021/lib/python3.7/site-packages/PyDynamic/model_estimation/fit_filter.py", line 137, in LSIIR
    freq_resp_to_fit, tau, omega, E, Na, Nb, inv
  File "~/python_venv/cim_2021/lib/python3.7/site-packages/PyDynamic/model_estimation/fit_filter.py", line 315, in _compute_actual_iir_least_squares_fit
    D = np.hstack((HEa, -Eb))
  File "<__array_function__ internals>", line 6, in hstack
  File "~/python_venv/cim_2021/lib/python3.7/site-packages/numpy/core/shape_base.py", line 343, in hstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)
```

**To Reproduce**
```python
from PyDynamic.model_estimation import LSIIR
import numpy as np

N = 10
f = np.arange(N)
Fs = 1.0
H = np.random.randn(N) + 1j*np.random.randn(N)
UH = np.diag(1 + np.random.rand(2*N))

res = LSIIR(H=H, UH=UH, Nb=3, Na=6, f=f, Fs=Fs, tau=2, inv=True, mc_runs=100, verbose=False)
```

**Expected behavior**
Method uses the covariance information and returns result instead of error.

**Environment:**
 - OS: Debian 10, Python 3.7
 - PyDynamic 2.0.0
 - numpy 1.21.2

**Comment by BjoernLudwigPTB** [comment]
This was resolved by merging #264.
